package com.quantorbital.core.model;

import java.time.Instant;

/**
 * Immutable time-series telemetry frame generated by satellite subsystems.
 */
public record TelemetryPacket(
    String satelliteId,
    Instant timestamp,
    double batteryTemperature,   // Celsius
    double fuelLevel,            // Percentage (0.0 - 100.0)
    double radiationLevel,       // rads/hour
    double velocity              // km/s
) {
    public TelemetryPacket {
        if (fuelLevel < 0.0 || fuelLevel > 100.0) {
            throw new IllegalArgumentException("Fuel level must be strictly between 0 and 100.");
        }
    }
}
